### ISSUE TITLE
Introduce a troubleshooting section in the readme / include preliminary checks in the installation

### ISSUE THREAD

**Issue by lvacabenitez** [oarriaga/paz#117]
Hi! I wanted to list here some issues I had while installing the library. Maybe this helps improve the installation procedure for others.

First of all (important mainly for people not having a proper python installation) I had to install python3 pip 
`sudo apt install python3-pip
`
python pip did not work for me. It was not clear which version will be needed.

Running   `pip3 install pypaz --user`
gave the following error:

 ```
Using cached https://files.pythonhosted.org/packages/38/a9/cd39fd25df434b5d9451dc266c12b72f68282a2b9bd5d7b4aa2d57d6c20e/opencv-python-4.4.0.44.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d9z0d2zk/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d9z0d2zk/opencv-python/
```
The problem was solved running    `pip3 install --upgrade pip`
But the following error was shown:

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

launchpadlib 1.10.6 requires testresources, which is not installed.
tensorflow 2.3.1 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.3 which is incompatible.

```
Running  `pip3 install pypaz --user --use-feature=2020-resolver`  solved that. I don't know if the aforementioned steps can be included so that they are done by the installation function?

Finally, in order to clone the repo,  `git clone git@github.com:oarriaga/paz.git`  did not work, but `git clone https://github.com/oarriaga/paz.git` did.

I hope this helps :)

**Comment by oarriaga** [comment]
Thank you @lvacabenitez ! I am sure this small tutorial for installing PAZ in Ubuntu would help whenever that are issues with opencv or pip. I will close this issue for now but feel free to open it if some other errors occur in your installation.
