### ISSUE TITLE
Building SSD model by loading available pretrained weights fail

### ISSUE THREAD

**Issue by DeepanChakravarthiPadmanabhan** [oarriaga/paz#150]
The currently available pretrained weights for the SSD model with the base weights and head weights combination as 'VOC' and None fails.

**Comment by DeepanChakravarthiPadmanabhan** [comment]
The loading fails because of a mismatch between weight variable names in the SSD model built-in PAZ and available pretrained weights. To fix this issue, the pretrained weights for the VOC-None combination are rectified by modifying the layer names directly in the hdf5 file and creating a new weight file.

**Comment by oarriaga** [comment]
Thank you for PR.
