### ISSUE TITLE
Doubts about the face detection module

### ISSUE THREAD

**Issue by David9591** [oarriaga/paz#154]
Hello, dear author! 
First of all thank you for your excellent work, and then I have a question: After browsing the project briefly, I found that the project uses HaarCascadeFrontalFace for face detection. As far as my personal experience is concerned, this detector is not accurate enough and should be eliminated. At present, opencv has a built-in SSD-based face detector with higher accuracy and faster speed. What are the considerations for not adopting it?  Or is there a better option in the project, but I didn’t notice it? 
Best wishes!

**Comment by oarriaga** [comment]
Hi, I am glad you like the project. The HaarCascade face detector was taken due to simplicity, and I agree that it should be replaced. Most likely by openCV's face detector using SSD or by our own face detector trained with EfficientDet. It would be great if anyone is interested in making a PR in this direction :)

**Comment by David9591** [comment]
> Hi, I am glad you like the project. The HaarCascade face detector was taken due to simplicity, and I agree that it should be replaced. Most likely by openCV's face detector using SSD or by our own face detector trained with EfficientDet. It would be great if anyone is interested in making a PR in this direction :)

Thank you for your meticulous answer. I have encountered a new problem in Emotion classification. I will open a new issue to ask you for advice, and I will close this issue. Thank you again for your excellent work！
