### ISSUE TITLE
Gender detection

### ISSUE THREAD

**Issue by Hyrtsi** [oarriaga/paz#209]
Greetings,

I found this repository (paz) from link in [this](https://github.com/oarriaga/face_classification) repository.

My goal is to have gender detection feature in this repository.  For some weird reason it's in [oarriaga/face_classification](https://github.com/oarriaga/face_classification) but not here even though it's mentioned in your research publication.

I have a few questions:
- Do the xception models support the weights in [oarriga/face_classification](https://github.com/oarriaga/face_classification) repository?
- Is it simple to output also the gender from the xception model? Is it just a matter of choosing the outputs?

I will start working on this feature myself and open a PR but some additional info will make my job easier :) thank you!

**Comment by oarriaga** [comment]
Hi thank you for the interest! Yes the PR would be most welcomed thank you.

I think one could use the same [xception model builder](https://github.com/oarriaga/paz/blob/master/paz/models/classification/xception.py) here.

The only problematic thing could be to load the weights directly. Maybe this can be done in a simple way by doing `old_repo_model.save_weights('weights.hdf5')` and then `new_repo_model.save_weights('weights.hdf5')`. I hope this can help you!

**Comment by Hyrtsi** [comment]
Ok, thank you for the hints. I'll try that as soon as I have time :)
