### ISSUE TITLE
Which version should I choose？

### ISSUE THREAD

**Issue by xufengyang0191** [oarriaga/paz#234]
Hello, Your work is very interesting! I sincerely want to install them to do some applications but the version of TensorFlow2.x don't seem to be clear. I don't know how to use it. Thanks for your reply!

**Comment by oarriaga** [comment]
@xufengyang0191 sorry for the late reply. I try to maintain everything with the latest version. I am right now using `tf 2.11.0`.

**Comment by xufengyang0191** [comment]
Oh, OK! Thanks for your reply~ I have successfully imported it in my code several days ago. It's pretty convenient, but if the reference documents canbe more detailed, it may be better for newcomers to get started.

**Comment by oarriaga** [comment]
Great! I am happy to hear you find it convenient. Which reference documents do you refer too? At the moment the examples are pretty raw, but some tutorials [about the components can be found here](https://oarriaga.github.io/paz/getting-started/introduction_to_processors/). Let me know how can I make it better :)
