### ISSUE TITLE
Recover open images data loader

### ISSUE THREAD

**Issue by oarriaga** [oarriaga/paz#278]
When refactoring the hand pose estimation. We lost some of the data loaders and generators. The most important of those was the OpenImages loader. Would it be possible to look back in to the git history and recover it?

**Comment by proneetsharma** [comment]
It's there in the [hand_detection](https://github.com/oarriaga/paz/tree/0c6a240d65047301d7a78b70bcace3a4abef9a25/examples/hand_detection) branch. Should I merge it with the master?

**Comment by oarriaga** [comment]
Yes please! Just the OpenImages DataLoader for now, also push to master in this same example directory. the data loading script that uses the `fiftyone` library, and the training script. Basically everything that we would need to train this model again. Hopefully after we have the EfficientDets we can retrain these models to be smaller and faster, as well as to include a face detector.
